# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ~salekseev
tagline:          'Random musings of a Systems Engineer'
description:      'Made by <a href="https://twitter.com/stas_alekseev" target="_blank">@stas_alekseev</a>.'
url:              http://salekseev.com
baseurl:          '/'
paginate:         5

author:
  name:           'Stas Alekseev'
  url:            https://twitter.com/stas_alekseev

# Custom vars
github:           https://github.com/salekseev
